project:
  type: website

website:
  title: "Seongjoon's Blog"
    
  navbar:

    left:
      - text: Deep_Learnig
        href: https://sjoon0305.github.io/Deep_Learning/
      - text: DeepXDE
        href: https://sjoon0305.github.io/DeepXDE_odes/
      - text: 2024 Data Science Project
        href: https://sjoon0305.github.io/2024_Data_Science_Project/
      - text: PyTorch Deep Learning Master
        href: https://sjoon0305.github.io/PyTorch_intro/

    right:
      - about.qmd
      - icon: github
        href: https://github.com/sjoon0305
      - icon: twitter
        href: https://sjoon0305.github.io/blog_test2/posts/Day2.html

format:
  html:
    theme: cosmo
    css: styles.css



