project:
  type: website

website:
  title: "Seongjoon's Blog"

  page-footer:
    border: true
    
  navbar:

    left:
      - text: Deep_Learnig
        href: https://sjoon0305.github.io/Deep_Learning/
      - text: Quarto-make blog
        href: https://sjoon0305.github.io/blog_test2/

      
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sjoon0305
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: false
    code-copy: false



